// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                    = new(Query)
	AutoCodeHistory      *autoCodeHistory
	AutoCodeHistoryField *autoCodeHistoryField
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	AutoCodeHistory = &Q.AutoCodeHistory
	AutoCodeHistoryField = &Q.AutoCodeHistoryField
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                   db,
		AutoCodeHistory:      newAutoCodeHistory(db, opts...),
		AutoCodeHistoryField: newAutoCodeHistoryField(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AutoCodeHistory      autoCodeHistory
	AutoCodeHistoryField autoCodeHistoryField
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                   db,
		AutoCodeHistory:      q.AutoCodeHistory.clone(db),
		AutoCodeHistoryField: q.AutoCodeHistoryField.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                   db,
		AutoCodeHistory:      q.AutoCodeHistory.replaceDB(db),
		AutoCodeHistoryField: q.AutoCodeHistoryField.replaceDB(db),
	}
}

type queryCtx struct {
	AutoCodeHistory      IAutoCodeHistoryDo
	AutoCodeHistoryField IAutoCodeHistoryFieldDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AutoCodeHistory:      q.AutoCodeHistory.WithContext(ctx),
		AutoCodeHistoryField: q.AutoCodeHistoryField.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	return &QueryTx{q.clone(q.db.Begin(opts...))}
}

type QueryTx struct{ *Query }

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
