// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: plugin/oss/config/oss.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Minio      *Minio      `protobuf:"bytes,1,opt,name=Minio,proto3" json:"Minio,omitempty"`
	AliyunOss  *AliyunOss  `protobuf:"bytes,2,opt,name=AliyunOss,proto3" json:"AliyunOss,omitempty"`
	HuaWeiObs  *HuaWeiObs  `protobuf:"bytes,3,opt,name=HuaWeiObs,proto3" json:"HuaWeiObs,omitempty"`
	QiniuKodo  *QiniuKodo  `protobuf:"bytes,4,opt,name=QiniuKodo,proto3" json:"QiniuKodo,omitempty"`
	TencentCos *TencentCos `protobuf:"bytes,5,opt,name=TencentCos,proto3" json:"TencentCos,omitempty"`
	LocalStore *LocalStore `protobuf:"bytes,6,opt,name=LocalStore,proto3" json:"LocalStore,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_oss_config_oss_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_oss_config_oss_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_plugin_oss_config_oss_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetMinio() *Minio {
	if x != nil {
		return x.Minio
	}
	return nil
}

func (x *Config) GetAliyunOss() *AliyunOss {
	if x != nil {
		return x.AliyunOss
	}
	return nil
}

func (x *Config) GetHuaWeiObs() *HuaWeiObs {
	if x != nil {
		return x.HuaWeiObs
	}
	return nil
}

func (x *Config) GetQiniuKodo() *QiniuKodo {
	if x != nil {
		return x.QiniuKodo
	}
	return nil
}

func (x *Config) GetTencentCos() *TencentCos {
	if x != nil {
		return x.TencentCos
	}
	return nil
}

func (x *Config) GetLocalStore() *LocalStore {
	if x != nil {
		return x.LocalStore
	}
	return nil
}

type Minio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// UseSsl 是否使用ssl
	UseSsl bool `protobuf:"varint,1,opt,name=UseSsl,proto3" json:"UseSsl,omitempty"`
	// Path 文件存储文件夹
	Path string `protobuf:"bytes,2,opt,name=Path,proto3" json:"Path,omitempty"`
	// Prefix 文件前缀 不填则为空
	Prefix string `protobuf:"bytes,3,opt,name=Prefix,proto3" json:"Prefix,omitempty"`
	// Token token
	Token string `protobuf:"bytes,4,opt,name=Token,proto3" json:"Token,omitempty"`
	// Bucket 存储桶名称
	Bucket string `protobuf:"bytes,5,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	// Domain 访问域名
	Domain string `protobuf:"bytes,6,opt,name=Domain,proto3" json:"Domain,omitempty"`
	// Endpoint endpoint
	Endpoint string `protobuf:"bytes,7,opt,name=Endpoint,proto3" json:"Endpoint,omitempty"`
	// AccessKey 秘钥AK
	AccessKey string `protobuf:"bytes,8,opt,name=AccessKey,proto3" json:"AccessKey,omitempty"`
	// SecretKey 秘钥SK
	SecretKey string `protobuf:"bytes,9,opt,name=SecretKey,proto3" json:"SecretKey,omitempty"`
	// ExpirationTime 过期时间
	ExpirationTime string `protobuf:"bytes,10,opt,name=ExpirationTime,proto3" json:"ExpirationTime,omitempty"`
}

func (x *Minio) Reset() {
	*x = Minio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_oss_config_oss_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Minio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Minio) ProtoMessage() {}

func (x *Minio) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_oss_config_oss_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Minio.ProtoReflect.Descriptor instead.
func (*Minio) Descriptor() ([]byte, []int) {
	return file_plugin_oss_config_oss_proto_rawDescGZIP(), []int{1}
}

func (x *Minio) GetUseSsl() bool {
	if x != nil {
		return x.UseSsl
	}
	return false
}

func (x *Minio) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Minio) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *Minio) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Minio) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *Minio) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Minio) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Minio) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *Minio) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *Minio) GetExpirationTime() string {
	if x != nil {
		return x.ExpirationTime
	}
	return ""
}

type AliyunOss struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Path 文件存储文件夹
	Path string `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	// Prefix 文件前缀 不填则为空
	Prefix string `protobuf:"bytes,2,opt,name=Prefix,proto3" json:"Prefix,omitempty"`
	// Bucket 存储桶名称
	Bucket string `protobuf:"bytes,3,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	// Domain 访问域名
	Domain string `protobuf:"bytes,4,opt,name=Domain,proto3" json:"Domain,omitempty"`
	// Endpoint 地域节点
	Endpoint string `protobuf:"bytes,5,opt,name=Endpoint,proto3" json:"Endpoint,omitempty"`
	// AccessKeyId 访问密钥 Id
	AccessKeyId string `protobuf:"bytes,6,opt,name=AccessKeyId,proto3" json:"AccessKeyId,omitempty"`
	// AccessKeySecret 访问密钥 Secret
	AccessKeySecret string `protobuf:"bytes,7,opt,name=AccessKeySecret,proto3" json:"AccessKeySecret,omitempty"`
}

func (x *AliyunOss) Reset() {
	*x = AliyunOss{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_oss_config_oss_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AliyunOss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliyunOss) ProtoMessage() {}

func (x *AliyunOss) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_oss_config_oss_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliyunOss.ProtoReflect.Descriptor instead.
func (*AliyunOss) Descriptor() ([]byte, []int) {
	return file_plugin_oss_config_oss_proto_rawDescGZIP(), []int{2}
}

func (x *AliyunOss) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AliyunOss) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *AliyunOss) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *AliyunOss) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *AliyunOss) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *AliyunOss) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *AliyunOss) GetAccessKeySecret() string {
	if x != nil {
		return x.AccessKeySecret
	}
	return ""
}

type HuaWeiObs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path      string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Bucket    string `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Endpoint  string `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	AccessKey string `protobuf:"bytes,4,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretKey string `protobuf:"bytes,5,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
}

func (x *HuaWeiObs) Reset() {
	*x = HuaWeiObs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_oss_config_oss_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HuaWeiObs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HuaWeiObs) ProtoMessage() {}

func (x *HuaWeiObs) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_oss_config_oss_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HuaWeiObs.ProtoReflect.Descriptor instead.
func (*HuaWeiObs) Descriptor() ([]byte, []int) {
	return file_plugin_oss_config_oss_proto_rawDescGZIP(), []int{3}
}

func (x *HuaWeiObs) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HuaWeiObs) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *HuaWeiObs) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *HuaWeiObs) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *HuaWeiObs) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

type LocalStore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Path 存储路径
	Path string `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	// Domain 访问路径
	Domain string `protobuf:"bytes,2,opt,name=Domain,proto3" json:"Domain,omitempty"`
}

func (x *LocalStore) Reset() {
	*x = LocalStore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_oss_config_oss_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalStore) ProtoMessage() {}

func (x *LocalStore) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_oss_config_oss_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalStore.ProtoReflect.Descriptor instead.
func (*LocalStore) Descriptor() ([]byte, []int) {
	return file_plugin_oss_config_oss_proto_rawDescGZIP(), []int{4}
}

func (x *LocalStore) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LocalStore) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type QiniuKodo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Path 文件存储文件夹
	Path string `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	// Prefix 文件前缀 不填则为空
	Prefix string `protobuf:"bytes,2,opt,name=Prefix,proto3" json:"Prefix,omitempty"`
	// Bucket 空间名称
	Bucket string `protobuf:"bytes,3,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	// Domain CDN加速域名
	Domain string `protobuf:"bytes,4,opt,name=Domain,proto3" json:"Domain,omitempty"`
	// AccessKey 秘钥AK
	AccessKey string `protobuf:"bytes,5,opt,name=AccessKey,proto3" json:"AccessKey,omitempty"`
	// SecretKey 秘钥SK
	SecretKey string `protobuf:"bytes,6,opt,name=SecretKey,proto3" json:"SecretKey,omitempty"`
	// UseHttps 是否使用https
	UseHttps bool `protobuf:"varint,7,opt,name=UseHttps,proto3" json:"UseHttps,omitempty"`
	// UseCdnDomains 是否使用cdn加速域名
	UseCdnDomains bool `protobuf:"varint,8,opt,name=UseCdnDomains,proto3" json:"UseCdnDomains,omitempty"`
}

func (x *QiniuKodo) Reset() {
	*x = QiniuKodo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_oss_config_oss_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QiniuKodo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QiniuKodo) ProtoMessage() {}

func (x *QiniuKodo) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_oss_config_oss_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QiniuKodo.ProtoReflect.Descriptor instead.
func (*QiniuKodo) Descriptor() ([]byte, []int) {
	return file_plugin_oss_config_oss_proto_rawDescGZIP(), []int{5}
}

func (x *QiniuKodo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *QiniuKodo) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *QiniuKodo) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *QiniuKodo) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *QiniuKodo) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *QiniuKodo) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *QiniuKodo) GetUseHttps() bool {
	if x != nil {
		return x.UseHttps
	}
	return false
}

func (x *QiniuKodo) GetUseCdnDomains() bool {
	if x != nil {
		return x.UseCdnDomains
	}
	return false
}

type TencentCos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Path 文件存储文件夹
	Path string `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	// Prefix 文件名前缀
	Prefix string `protobuf:"bytes,2,opt,name=Prefix,proto3" json:"Prefix,omitempty"`
	// Bucket 桶名
	Bucket string `protobuf:"bytes,3,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	// Domain 访问域名
	Domain string `protobuf:"bytes,4,opt,name=Domain,proto3" json:"Domain,omitempty"`
	// SecretKey 访问密钥 Id
	SecretId string `protobuf:"bytes,5,opt,name=SecretId,proto3" json:"SecretId,omitempty"`
	// SecretKey 访问密钥 Secret
	SecretKey string `protobuf:"bytes,6,opt,name=SecretKey,proto3" json:"SecretKey,omitempty"`
}

func (x *TencentCos) Reset() {
	*x = TencentCos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_oss_config_oss_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TencentCos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TencentCos) ProtoMessage() {}

func (x *TencentCos) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_oss_config_oss_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TencentCos.ProtoReflect.Descriptor instead.
func (*TencentCos) Descriptor() ([]byte, []int) {
	return file_plugin_oss_config_oss_proto_rawDescGZIP(), []int{6}
}

func (x *TencentCos) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TencentCos) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *TencentCos) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *TencentCos) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *TencentCos) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *TencentCos) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

var File_plugin_oss_config_oss_proto protoreflect.FileDescriptor

var file_plugin_oss_config_oss_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x6f, 0x73, 0x73, 0x2f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2f, 0x6f, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6f,
	0x73, 0x73, 0x22, 0x96, 0x02, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x20, 0x0a,
	0x05, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6f,
	0x73, 0x73, 0x2e, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x52, 0x05, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x12,
	0x2c, 0x0a, 0x09, 0x41, 0x6c, 0x69, 0x79, 0x75, 0x6e, 0x4f, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6f, 0x73, 0x73, 0x2e, 0x41, 0x6c, 0x69, 0x79, 0x75, 0x6e, 0x4f,
	0x73, 0x73, 0x52, 0x09, 0x41, 0x6c, 0x69, 0x79, 0x75, 0x6e, 0x4f, 0x73, 0x73, 0x12, 0x2c, 0x0a,
	0x09, 0x48, 0x75, 0x61, 0x57, 0x65, 0x69, 0x4f, 0x62, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x6f, 0x73, 0x73, 0x2e, 0x48, 0x75, 0x61, 0x57, 0x65, 0x69, 0x4f, 0x62, 0x73,
	0x52, 0x09, 0x48, 0x75, 0x61, 0x57, 0x65, 0x69, 0x4f, 0x62, 0x73, 0x12, 0x2c, 0x0a, 0x09, 0x51,
	0x69, 0x6e, 0x69, 0x75, 0x4b, 0x6f, 0x64, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x6f, 0x73, 0x73, 0x2e, 0x51, 0x69, 0x6e, 0x69, 0x75, 0x4b, 0x6f, 0x64, 0x6f, 0x52, 0x09,
	0x51, 0x69, 0x6e, 0x69, 0x75, 0x4b, 0x6f, 0x64, 0x6f, 0x12, 0x2f, 0x0a, 0x0a, 0x54, 0x65, 0x6e,
	0x63, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x6f, 0x73, 0x73, 0x2e, 0x54, 0x65, 0x6e, 0x63, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x73, 0x52, 0x0a,
	0x54, 0x65, 0x6e, 0x63, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x73, 0x12, 0x2f, 0x0a, 0x0a, 0x4c, 0x6f,
	0x63, 0x61, 0x6c, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x6f, 0x73, 0x73, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52,
	0x0a, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x22, 0x91, 0x02, 0x0a, 0x05,
	0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x53, 0x73, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x55, 0x73, 0x65, 0x53, 0x73, 0x6c, 0x12, 0x12, 0x0a,
	0x04, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x61, 0x74,
	0x68, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x41,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x26, 0x0a, 0x0e, 0x45, 0x78, 0x70, 0x69, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x45, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x22,
	0xcf, 0x01, 0x0a, 0x09, 0x41, 0x6c, 0x69, 0x79, 0x75, 0x6e, 0x4f, 0x73, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x61, 0x74,
	0x68, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x75, 0x63,
	0x6b, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x42, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x45, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b,
	0x65, 0x79, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x41, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x4b, 0x65, 0x79, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x4b, 0x65, 0x79, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x22, 0x91, 0x01, 0x0a, 0x09, 0x48, 0x75, 0x61, 0x57, 0x65, 0x69, 0x4f, 0x62, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x65,
	0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65,
	0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x4b, 0x65, 0x79, 0x22, 0x38, 0x0a, 0x0a, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x50, 0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x22,
	0xe5, 0x01, 0x0a, 0x09, 0x51, 0x69, 0x6e, 0x69, 0x75, 0x4b, 0x6f, 0x64, 0x6f, 0x12, 0x12, 0x0a,
	0x04, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x61, 0x74,
	0x68, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x75, 0x63,
	0x6b, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x42, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x41, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x4b, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x48, 0x74, 0x74, 0x70,
	0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x55, 0x73, 0x65, 0x48, 0x74, 0x74, 0x70,
	0x73, 0x12, 0x24, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x43, 0x64, 0x6e, 0x44, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x55, 0x73, 0x65, 0x43, 0x64, 0x6e,
	0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x22, 0xa2, 0x01, 0x0a, 0x0a, 0x54, 0x65, 0x6e, 0x63,
	0x65, 0x6e, 0x74, 0x43, 0x6f, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x72,
	0x65, 0x66, 0x69, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x72, 0x65, 0x66,
	0x69, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x44, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x49, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x42, 0x15, 0x5a, 0x13,
	0x2e, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x6f, 0x73, 0x73, 0x2f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_plugin_oss_config_oss_proto_rawDescOnce sync.Once
	file_plugin_oss_config_oss_proto_rawDescData = file_plugin_oss_config_oss_proto_rawDesc
)

func file_plugin_oss_config_oss_proto_rawDescGZIP() []byte {
	file_plugin_oss_config_oss_proto_rawDescOnce.Do(func() {
		file_plugin_oss_config_oss_proto_rawDescData = protoimpl.X.CompressGZIP(file_plugin_oss_config_oss_proto_rawDescData)
	})
	return file_plugin_oss_config_oss_proto_rawDescData
}

var file_plugin_oss_config_oss_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_plugin_oss_config_oss_proto_goTypes = []interface{}{
	(*Config)(nil),     // 0: oss.Config
	(*Minio)(nil),      // 1: oss.Minio
	(*AliyunOss)(nil),  // 2: oss.AliyunOss
	(*HuaWeiObs)(nil),  // 3: oss.HuaWeiObs
	(*LocalStore)(nil), // 4: oss.LocalStore
	(*QiniuKodo)(nil),  // 5: oss.QiniuKodo
	(*TencentCos)(nil), // 6: oss.TencentCos
}
var file_plugin_oss_config_oss_proto_depIdxs = []int32{
	1, // 0: oss.Config.Minio:type_name -> oss.Minio
	2, // 1: oss.Config.AliyunOss:type_name -> oss.AliyunOss
	3, // 2: oss.Config.HuaWeiObs:type_name -> oss.HuaWeiObs
	5, // 3: oss.Config.QiniuKodo:type_name -> oss.QiniuKodo
	6, // 4: oss.Config.TencentCos:type_name -> oss.TencentCos
	4, // 5: oss.Config.LocalStore:type_name -> oss.LocalStore
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_plugin_oss_config_oss_proto_init() }
func file_plugin_oss_config_oss_proto_init() {
	if File_plugin_oss_config_oss_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_plugin_oss_config_oss_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_oss_config_oss_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Minio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_oss_config_oss_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AliyunOss); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_oss_config_oss_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HuaWeiObs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_oss_config_oss_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalStore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_oss_config_oss_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QiniuKodo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_oss_config_oss_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TencentCos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_plugin_oss_config_oss_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugin_oss_config_oss_proto_goTypes,
		DependencyIndexes: file_plugin_oss_config_oss_proto_depIdxs,
		MessageInfos:      file_plugin_oss_config_oss_proto_msgTypes,
	}.Build()
	File_plugin_oss_config_oss_proto = out.File
	file_plugin_oss_config_oss_proto_rawDesc = nil
	file_plugin_oss_config_oss_proto_goTypes = nil
	file_plugin_oss_config_oss_proto_depIdxs = nil
}
